POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testi blogi",
  "author": "Testi Ukko",
  "url": "http://testi.test",
  "likes": 7
}

// SCHEMA
//title: String,
//author: String,
//url: String,
//likes: Number
