POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "elellelelelele",
  "author": "Pertti",
  "url": "http://testi.test",
  "likes": 645
}

// SCHEMA
//title: String,
//author: String,
//url: String,
//likes: Number
